# Skalmans bomb ass site aight
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Skalmans site aight
email: fuckoff@private.com
description: > # GTFO
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: GTFO
github_username:  GTFO

# Build settings
markdown: kramdown
